# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Deployment status
description: Creates and manages GitHub deployments and releases on target repositories

inputs:
  command:
    description: Command to run. Supported values delete-deployment, delete-release, get-all-deployments, get-all-releases, update-deployment, update-release
    required: false
    type: string
    default: update-deployment
  github_org:
    description: GitHub organization hosting the target repository
    required: false
    type: string
    default: mozilla
  repository:
    description: GitHub repository to target
    type: string
    required: true
  environment_url:
    description: Environment URL to set in deployment
    type: string
    required: false 
    default: ""
  state:
    description: State of deployment. Supported values in_progress, success, failed
    type: choice
    default: in_progress
  environment:
    description: Target deployment environment
    type: string
    default: staging
  ref: 
    description: Deployed git ref
    type: string
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - -r
    - ${{ inputs.repository }}
    - -o
    - ${{ inputs.github_org }}
    - ${{ inputs.command }}
    - --tag
    - ${{ inputs.ref }}
    - --environment
    - ${{ inputs.environment }}
    - --state
    -  ${{ inputs.state }}
    - --environment_url
    - ${{ inputs.environment_url }}


