# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Deploy Helm Chart
author: Mozilla
description: Obtain credentials for GKE cluster & install Helm chart

inputs:
  app_name:
    description: Name of tenant app to deploy to, e.g. testapp1
    required: true
  tag_value_path:
    description: Path to Helm value for the image tag
    default: image.tag
    required: false
  image_tag:
    description: Name of the image tag
    required: true
  infra_repo:
    description: Infrastructure repository contain Helm charts, e.g. mozilla/helm-charts
    required: true
  infra_repo_ref:
    description: Infrastructure repository git reference to checkout, defaults to `main`
    required: false
    default: main
  infra_repo_ssh_key:
    description: SSH key with permissions to checkout infrastructure repository, typically a deploy key
    required: true
  env_name:
    description: Name of tenant env to deploy to, e.g. dev
    required: true
  realm_name:
    description: Name of tenant realm to deploy to, e.g. nonprod
    required: true
  workload_identity_pool_project_number:
    description: Project number of workload identity pool used for OIDC authentication
    required: true
  k8s_cluster_name:
    description: Kubernetes cluster name, e.g. mozilla-nonprod
    required: true
  k8s_cluster_location:
    description: Kubernetes cluster location, e.g. us-west1
    required: true
  k8s_cluster_project:
    description: Kubernetes cluster project, e.g. mozilla-firefox-nonprod
    required: true
  helm_release_name:
    description: Helm chart release name, defaults to `gha`
    required: false
    default: gha
  helm_chart_path:
    description: Helm chart path within infrastructure repository , e.g. testapp1/k8s/testapp1/
    required: true
  helm_timeout:
    description: Helm chart timeout, defaults to `600s`
    required: false
    default: "600s"
  helm_values:
    description: Helm values specified with '--set' flag value, e.g. "--set 'foo.bar=value'"
    required: false
    default: ""
  helm_value_files:
    description: Helm chart value files within the infrastructure repository specified with "-f" flag value, e.g. "-f values-dev.yaml -f values-dev-additional.yaml", defaults to "-f values-$env_name.yaml"
    required: false
    default: ""
  project_id:
    description: GCP project_id used to construct deployment service account. Use this when your project_id doesn't follow the normal patterns, i.e.  uses a random id in project_id.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: checkout the infra repo ${{ inputs.infra_repo }}
      uses: actions/checkout@v3
      with:
        path: infra_repo
        repository: ${{ inputs.infra_repo }}
        ref: ${{ inputs.infra_repo_ref }}
        ssh-key: ${{ inputs.infra_repo_ssh_key }}

    - id: deployment_service_account
      name: deployment service account
      shell: bash
      run: |
        if [[ "${{ inputs.project_id }}" == "" ]]; then
        echo "SERVICE_ACCOUNT=deploy-${{ inputs.env_name }}@moz-fx-${{ inputs.app_name }}-${{ inputs.realm_name }}.iam.gserviceaccount.com" >> $GITHUB_OUTPUT
        else
        echo "SERVICE_ACCOUNT=deploy-${{ inputs.env_name }}@${{ inputs.project_id }}.iam.gserviceaccount.com" >> $GITHUB_OUTPUT
        fi

    - name: gcp authentication
      uses: google-github-actions/auth@v1
      with:
        service_account: ${{ steps.deployment_service_account.outputs.SERVICE_ACCOUNT }}
        workload_identity_provider: projects/${{ inputs.workload_identity_pool_project_number }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions

    - name: get gke credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ inputs.k8s_cluster_name }}
        location: ${{ inputs.k8s_cluster_location }}
        project_id: ${{ inputs.k8s_cluster_project }}

    - name: set the helm values flag
      id: helm_values
      shell: bash
      run: |
        if [[ "${{ inputs.helm_value_files }}" == "" ]]; then
          echo "FILES=-f values-${{ inputs.env_name }}.yaml" >> $GITHUB_OUTPUT
        else
          echo "FILES=${{ inputs.helm_value_files }}" >> $GITHUB_OUTPUT
        fi

    - name: helm version
      shell: bash
      run: helm version

    - name: helm list
      shell: bash
      run: helm list -n ${{ inputs.app_name }}-${{ inputs.env_name }} -a

    # Workaround for --dependency-update flag failing to update OCI packaged charts
    - name: helm dependency update
      shell: bash
      working-directory: infra_repo/${{ inputs.helm_chart_path }}
      run: helm dependency update

    # FIXME
    # - Look at adding --atomic or --wait as flags
    - name: helm install
      shell: bash
      working-directory: infra_repo/${{ inputs.helm_chart_path }}
      run: |
        helm upgrade ${{ inputs.helm_release_name }} .              \
        --install                                                   \
        --dependency-update                                         \
        --namespace ${{ inputs.app_name }}-${{ inputs.env_name }}   \
        ${{ steps.helm_values.outputs.FILES }}                      \
        --set ${{ inputs.tag_value_path }}=${{ inputs.image_tag }}  \
        --timeout ${{ inputs.helm_timeout }}                        \
        ${{ inputs.helm_values }}

    # List installed charts after upgrade
    - name: helm list
      shell: bash
      run: helm list -n ${{ inputs.app_name }}-${{ inputs.env_name }} -a

    - name: helm app version
      id: helm_app_version
      shell: bash
      run: |
        helm list \
        --filter ${{ inputs.helm_release_name }} \
        --namespace ${{ inputs.app_name }}-${{ inputs.env_name }}   \
        --no-headers | awk '{printf "app=%s",$10}' | tee $GITHUB_OUTPUT

    - name: helm chart version
      id: helm_chart_version
      shell: bash
      run: |
        helm list \
        --filter ${{ inputs.helm_release_name }} \
        --namespace ${{ inputs.app_name }}-${{ inputs.env_name }}   \
        --no-headers | awk '{printf "chart=%s",$9}' | tee $GITHUB_OUTPUT
